lsi: false
safe: true
incremental: false
highlighter: rouge
author: Brian Schnepp
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: rdiscount
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
